<a href="https://colab.research.google.com/github/fls2134/Session-2/blob/main/se2_numpy_ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 라이브러리 import

In [4]:
import numpy as np

## NumPy 배열 생성 (기본적인 리스트 변환)

In [5]:
arr = np.array([1, 2, 3, 4, 5])
print("1D 배열:", arr)

1D 배열: [1 2 3 4 5]


## 2차원 배열 (행렬) 생성

In [6]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("2D 배열:\n", matrix)

2D 배열:
 [[1 2 3]
 [4 5 6]]


## 배열의 기본 정보 확인


In [7]:
print("배열 크기:", matrix.shape)  # (2,3) → 2행 3열
print("배열 차원:", matrix.ndim)   # 2차원 배열
print("배열 데이터 타입:", matrix.dtype)  # int64 (or int32)

배열 크기: (2, 3)
배열 차원: 2
배열 데이터 타입: int64


## 난수 생성


In [8]:
random_arr = np.random.rand(3, 3)  # 3x3 랜덤 행렬 (0~1 사이 값)
print("랜덤 배열:\n", random_arr)

랜덤 배열:
 [[0.69964646 0.79141173 0.47607318]
 [0.17338872 0.87895512 0.39956563]
 [0.78113816 0.94223778 0.44967053]]


## 기본 연산 (벡터 연산 가능)

In [9]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("덧셈:", a + b)  # [11 22 33]
print("곱셈:", a * b)  # [10 40 90]

덧셈: [11 22 33]
곱셈: [10 40 90]


## 행렬 곱셈 (dot product)


In [10]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("행렬 곱 (A @ B):\n", A @ B)  # 또는 np.dot(A, B)

행렬 곱 (A @ B):
 [[19 22]
 [43 50]]


## 통계 연산


In [11]:
data = np.array([10, 20, 30, 40, 50])
print("평균:", np.mean(data))  # 30.0
print("표준편차:", np.std(data))  # 14.14
print("최댓값:", np.max(data))  # 50
print("최솟값:", np.min(data))  # 10

평균: 30.0
표준편차: 14.142135623730951
최댓값: 50
최솟값: 10
